class people::bhiles {
  include chrome
  #include onepassword
  include dropbox
  include textwrangler
  include adium
  include quicksilver
  include divvy
  include virtualbox
  include wget
  include skype
  include rdio
  include caffeine
  include macvim
  include gimp
  include zsh
  include ohmyzsh
  include adobe_reader
  include osx::global::disable_remote_control_ir_receiver
  include osx::dock::autohide
  include osx::dock::clear_dock
  include osx::dock::dim_hidden_apps
  include java
  include clojure
  include tiny_alarm
  include vagrant
  include postgresql
  #include zsh_notifier
  include slack
  include graphviz
  include googlevoiceandvideoplugin
  #include libreoffice
  include emacs
  #include fluid
  include s3cmd
  include docker
  include dash
  include linkinus
  include maven
  include zeromq
  include libtool
  include memcached
  #include memcached::lib
  include phantomjs::1_9_0
}
